DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS chitiethoadon;
DROP TABLE IF EXISTS chitiethopdong;
DROP TABLE IF EXISTS hoadon;
DROP TABLE IF EXISTS hopdong;
DROP TABLE IF EXISTS khachhang;
DROP TABLE IF EXISTS khuvuc;
DROP TABLE IF EXISTS phong;